name: meteo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  page_view_dot_indicator: ^2.0.0
  get: ^4.6.5
  flutter_countdown_timer: ^4.1.0
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  percent_indicator: ^4.2.3
  async: ^2.10.0
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.1
  json_annotation: ^4.8.1
  dio: ^5.1.2
  logger: ^1.3.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

  # Ajout de la dépendance google_fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logoo.png"


flutter:
  assets:
    - assets/images/

  uses-material-design: true

